name: Update the Quilt Meta server
author: QuiltMC
description: This action updates the content of the Quilt Meta server

inputs:
  b2-key-id:
    description: The B2 key ID to use for uploading to the B2 bucket
    required: true
  b2-key:
    description: The B2 key to use for uploading to the B2 bucket
    required: true

runs:
  using: docker
  image: ghcr.io/quiltmc/update-quilt-meta:latest
  args:
    - ${{ inputs.b2-key-id }}
    - ${{ inputs.b2-key }}