name: Manually run the action

on:
  workflow_dispatch:

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run the action
      uses: ./
      with:
        b2-key-id: ${{ secrets.META_B2_KEY_ID }}
        b2-key: ${{ secrets.META_B2_KEY }}